---
name: on_saysomething
pack: hello_st2
description: Chatops demo
enabled: true
trigger:
    type: core.st2.webhook
    parameters:
      url: messages3
action:
    ref: chatops.post_message
    parameters:
      roomId: Y2lzY29zcGFyazovL3VzL1JPT00vNjNmZTg4ZjAtYzY4Zi0xMWVhLTkyODItN2RlNWEzMzUwNzVl
