---
name: on_get_room_details_event
pack: hello_st2
description: Chatops demo
enabled: true
trigger:
    type: hello_st2.event2
action:
    ref: cisco_spark.get_room
    parameters:
      roomId: Y2lzY29zcGFyazovL3VzL1JPT00vODhiZjMyMjAtYzAzNi0xMWVhLTk0ZmEtMDFhYjAzYjFlNzc2
