---
name: on_integration_properties_fetch
pack: hello_st2
description: Sample rule firing on hello_st2.integration_properties_fetch.
enabled: true
trigger:
    type: hello_st2.integration_properties_fetch
action:
    ref: hello_st2.greet
    parameters:
        greeting: "{{trigger.greeting}}"
